### ISSUE TITLE
Is this the "Team Project Health" extension?

### ISSUE THREAD

**Issue by nschonni** [ALM-Rangers/Visualize-Team-Project-Health-Widgets#1]
Wondering if this repo is supposed to hold the extension https://marketplace.visualstudio.com/items?itemName=ms-devlabs.TeamProjectHealth

**Comment by wpschaub** [comment]
Yes it is, but we have not yet migrated the codebase from our private repo here. Watch the space, we're busy preparing the codebase.

**Comment by nschonni** [comment]
Thanks, just noticed that a new version was released on the marketplace, but GH is usually the only place to tell what changed since the last one :smile:

**Comment by wpschaub** [comment]
I recommend that you bookmark **[aka.ms.vsar](https://aka.ms/vsar)** (vsar == Visual Studio ALM Rangers) and colick on the RELEASES tile. We're keeping a high-level journal of releases and what's changed there.

**Comment by nschonni** [comment]
It's in my RSS feed, and I know there is that one post with the release notes for all of the tools. The benefit of tags and releases on GitHub is that you get an email if you're watching the repo
