### ISSUE TITLE
I want to track any changes that made by my team, will this extension work?

### ISSUE THREAD

**Issue by BoYuanWANG1989** [ALM-Rangers/Visualize-Team-Project-Health-Widgets#29]
I want to track any changes that made by my team, will this extension work?
include any new comment.

**Comment by wpschaub** [comment]
The extension does not track changes, only the current state (health) of one or more builds and releases. Review the documentation and give the extension a try to confirm, but I do not believe it meets your requirements - https://marketplace.visualstudio.com/items?itemName=ms-devlabs.TeamProjectHealth.
