### ISSUE TITLE
widget return erreur ''Promise' is undefined

### ISSUE THREAD

**Issue by Bhuard1** [ALM-Rangers/Visualize-Team-Project-Health-Widgets#3]
Hi,

On promise 2017 CU3, version 1.2.62

When I add any of the build/release widgets get erreur
'Promise' is undefined

Any help would be appreciated

**Comment by wpschaub** [comment]
Which browser are you using? We're aware of aan issue with Internet Explorer (IE) -  _Until a Promise Polyfill hotfix is added to the web platform of TFS on-prem, this extension is not supported with Internet Explorer (IE) 11.0._

**Comment by Bhuard1** [comment]
Correct, IE11, sorry, missing the release note.

Thanks

**Comment by wpschaub** [comment]
Can you test / use a different browser in your environment?

**Comment by Bhuard1** [comment]
Yes, Chrome is fine, we still use IE11 at our company (we have not gone to edge yet).

For my purposes this will be fine. I can tell easily communicate to use chrome for a given dashboard (if people ever navigate to it).

Thanks.
