### ISSUE TITLE
Build health details : cannot open build by link

### ISSUE THREAD

**Issue by Bakanych** [ALM-Rangers/Visualize-Team-Project-Health-Widgets#4]
I have these wonderful widgets installed for our TFS 2018 onprem. When I open build info by clicking on Build health details widget from the dashboard I have an error:
![image](https://user-images.githubusercontent.com/17307409/34858259-362a5d5e-f78a-11e7-8480-9cd4e24040d9.png)

Does this extension fully support TFS 2018 onprem?

**Comment by WouterDeKort** [comment]
Hi @Bakanych,

thanks for reporting the issue! I've been able to reproduce it locally and I'm now investigating the issue with the help of the product group. 

As soon as I have a fix, I'll publish it and update this issue.

Kind regards,

Wouter

**Comment by WouterDeKort** [comment]
Hi @Bakanych ,

I've identified the issue and submitted a fix. The extension is currently being tested by the ALM Rangers to make sure everything works as expected and I didn't break anything. Once that's done a new version will be released to the marketplace.

I'll let you know when the new version is available.

Wouter

**Comment by WouterDeKort** [comment]
Hi @Bakanych,

the new version is released to the marketplace! Can you please install it and let me know if everything works OK?

I've also published a blog post detailing the fix I made: https://blogs.msdn.microsoft.com/visualstudioalmrangers/2018/01/16/using-the-navigationservice-in-your-vsts-and-tfs-extension/

Thank for reporting this,
Wouter

**Comment by Bakanych** [comment]
hi @WouterDeKort 
Thank you so much for this quick fix. It works now!
