### ISSUE TITLE
Builds with similar names show up in Build Health Overview

### ISSUE THREAD

**Issue by Sjors-Boom** [ALM-Rangers/Visualize-Team-Project-Health-Widgets#5]
## Build definitions with similar names are included in results.

**Steps to reproduce**

1. Create builds with similar names: `Foo.Bar` and `Foo.Bar.Gated`

2. Configure Build Health Overview only for build `Foo.Bar.Gated`
3. Run both builds

**Result**

The overview shows results from both build definitions.

**Investigation**
This line is the culprit:
`definitions = definitions.filter(def => customSettings.selectedDefinitions.indexOf(def.name) != -1);`

`Foo.Bar` is present within string `Foo.Bar.Build`
Thus not filtered from the original set of build definitions

**proposed solutions**

1. split `customSettings.selectedDefinitions` and check for full match
2. when selecting builds store the build id's in `customSettings.selectedDefinitions` (note: when a build is regenerated and gets a new id it won't be in the results)

**Comment by WouterDeKort** [comment]
Hi @Sjors-Boom,

thanks for bringing this up and even working on a fix! I'm currently working on a huge refactor for TPH to follow the latest guidance and do some cleanup before we start working on new features. If you do a pull request I'll merge it in and make sure that it goes live with the other refactorings.

Thanks for helping us out!

Wouter

**Comment by jaalvarezvi** [comment]
Dear all,

Thank you very much for the work and support.

We are facing the same issue. For what I see, this should be fixed! Could you please lend us a hand with this problem? What is the current status of this issue?

Thank you a lot!

**Comment by TheNitek** [comment]
This fix has not yet been released, has it? Any plans to do this soon?
